---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: nginx
      containers:
      - image: eu.gcr.io/xamaral/static-web:v0.0.7
        name: nginx
